### ISSUE TITLE
Create UTs for the types, defaults, etc

### ISSUE THREAD

**Issue by nachocano** [googleinterns/knative-source-mongodb#11]
**Problem**
UTs for the APIs related files

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Contributor

**Exit Criteria**
Types unit tested

**Additional context (optional)**
https://github.com/google/knative-gcp/blob/master/pkg/apis/events/v1alpha1/cloudauditlogssource_defaults_test.go

**Comment by nachocano** [comment]
Created this separate issue for UTs for the types. It can be done together with https://github.com/googleinterns/knative-source-mongodb/issues/3 if you'd like:

**Comment by selim5** [comment]
Will close this when #3 will be closed!
