### ISSUE TITLE
UTs for Receive Adapter

### ISSUE THREAD

**Issue by nachocano** [googleinterns/knative-source-mongodb#18]
**Problem**
We should write UTs for our Receive Adapter

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Contributor

**Exit Criteria**
The receive adapter is unit tested

**Additional context (optional)**
https://github.com/knative-sandbox/sample-source/tree/master/pkg/adapter

**Comment by selim5** [comment]
Useful link for mongo go driver UT
https://medium.com/better-programming/unit-testing-code-using-the-mongo-go-driver-in-golang-7166d1aa72c0
