### ISSUE TITLE
Interact with Mongodb though CLI

### ISSUE THREAD

**Issue by selim5** [googleinterns/knative-source-mongodb#19]
**Problem**
Need to figure out how to interact with the mongodb instance through the CLI so that we can standardise testing and the tutorials since so far I am doing it through the Ops Manager UI.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?
User
Dev

**Additional context (optional)**
Figure out where the `mongo` commands need to be ran ex. in the Cluster on a new pod, locally, etc...

How to connect to the db on cluster https://docs.mongodb.com/kubernetes-operator/master/tutorial/connect-from-inside-k8s/

**Comment by nachocano** [comment]
Thanks for creating this @selim5 !!!
Otherwise we will forget!

**Comment by selim5** [comment]
Found a way to add stuff and interact with db in go 
https://pkg.go.dev/go.mongodb.org/mongo-driver/mongo?tab=doc

**Comment by selim5** [comment]
* Add stuff ```podcastResult, err := podcastsCollection.InsertOne(ctx, bson.D{
    {"title", "The Polyglot Developer Podcast"},
    {"author", "Nic Raboy"},
    {"tags", bson.A{"development", "programming", "coding"}},
})```
* Add multiple ```episodeResult, err := episodesCollection.InsertMany(ctx, []interface{}{
    bson.D{
        {"podcast", podcastResult.InsertedID},
        {"title", "GraphQL for API Development"},
        {"description", "Learn about GraphQL from the co-creator of GraphQL, Lee Byron."},
        {"duration", 25},
    },
    bson.D{
        {"podcast", podcastResult.InsertedID},
        {"title", "Progressive Web Application Development"},
        {"description", "Learn about PWA development with Tara Manicsic."},
        {"duration", 32},
    },
})```
* Check if thing was added `err = collection.FindOne(ctx, filter).Decode(&result)`
* Delete stuff `result, err := podcastsCollection.DeleteOne(ctx, bson.M{"title": "The Polyglot Developer Podcast"})`
