### ISSUE TITLE
Install MongoDB in the cluster

### ISSUE THREAD

**Issue by nachocano** [googleinterns/knative-source-mongodb#6]
**Problem**
Need to install MongoDB in our cluster, and write the instructions in the README

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Developer

**Exit Criteria**
MongoDB installed in the cluster

**Comment by selim5** [comment]
Installed a standalone mongo db instance on the gke cluster, along withe ops manager operator required to make things work. **Need to add full documentation to Readme**

**Comment by nachocano** [comment]
Link to the instructions for future reference: https://docs.mongodb.com/kubernetes-operator/master/tutorial/deploy-standalone/

**Comment by selim5** [comment]
and https://www.mongodb.com/blog/post/running-mongodb-ops-manager-in-kubernetes#:~:text=The%20MongoDB%20Enterprise%20Kubernetes%20Operator%2C%20or%20simply%20the%20Operator%2C%20manages,changing%20these%20settings%20as%20needed. to setup the operator
